[versions]
agp = "8.9.3"
kotlin = "2.1.21"
composeBom = "2025.06.01"
activityCompose = "1.10.1"
coreKtx = "1.16.0"
tvMaterial = "1.0.1"
coroutines = "1.9.0"
nanohttpd = "2.3.1"
junit = "4.13.2"
orgJson = "20240303"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
tv-material = { module = "androidx.tv:tv-material", version.ref = "tvMaterial" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
junit = { module = "junit:junit", version.ref = "junit" }
org-json = { module = "org.json:json", version.ref = "orgJson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
